# Welcome to Jekyll!
#

# Site settings
title: Artificial Intelligence Mentor
description: |
  This is your personal study Mentor. 
  His sacred mission is to help you in exploring new fields or extending your knowledge by generating a nicely designed courses. 
  The materials of the courses are always to be built personally for you and adapted to your level and free time. 
  There are various materials sources and types updating daily and brought to you for free. 

owner: AI Mentor # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@aimentor.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aimentor.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/aimentorio
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/aagdinsights
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

gems:
  - jekyll-seo-tag